version: '3'
services:
  cnscud-redis:
    image: redis:5.0
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    restart: on-failure
    container_name: cnscud-redis
    ## use the hostname in project
    hostname: cd-rd1.cnscud.com

  ## original zookeeper
#  cnscud-zookeeper:
#    image: wurstmeister/zookeeper
#    volumes:
#      - ./data/zookeeper/data:/data
#      - ./data/zookeeper/logs:/datalog
#    container_name: cnscud-zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#    restart: always
#    hostname: cd-zk1.cnscud.com

  cnscud-zookeeper:
    build:
      context: ./config/zookeeper
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/logs:/datalog
    container_name: cnscud-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: on-failure
    ## use the hostname in project
    hostname: cd-zk1.cnscud.com
    image: cnscud/cavedemo/zookeeper

  # 如果需要保存数据, 则设置data外部绑定volumn
  cnscud-kafka:
    image: wurstmeister/kafka
    volumes:
      - ./data/kafka:/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: cd-mq1.cnscud.com
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: cd-zk1.cnscud.com:2181/cnscud-kafka
    restart: on-failure
    container_name: cnscud-kafka
    ## use the hostname in project
    hostname: cd-mq1.cnscud.com
    depends_on:
      - cnscud-zookeeper

  cnscud-mysql5:
    build:
      context: ./config/mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/init:/docker-entrypoint-initdb.d/
      - ./config/mysql/sql:/opt/sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    restart: on-failure
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: cnscud-mysql5
    ## use the hostname in project
    hostname: cd-db1.cnscud.com
    image: cnscud/cavedemo/mysql5

  ms-fundmain-service:
    build:
      context: ./ms-fundmain/ms-fundmain-service
    ports:
      - "9001:9001"
#    environment:
#      ZK_HOSTS: cd-zk1.cnscud.com:2181
    restart: always
    container_name: ms-fundmain-service
    hostname: ms-fundmain-service
    image: cnscud/cavedemo/ms-fundmain-service
    depends_on:
      - cnscud-zookeeper
      - cnscud-redis
      - cnscud-mysql5
      - cnscud-kafka

  ms-gateway:
    build:
      context: ./ms-gateway
    ports:
      - "8900:8900"
    restart: always
    container_name: ms-gateway
    hostname: ms-gateway
    image: cnscud/cavedemo/ms-gateway
    depends_on:
      - ms-fundmain-service

  demo-web:
    build:
      context: ./web
    ports:
      - "8000:8000"
    restart: always
    container_name: demo-web
    hostname: demo.cnscud.com
    image: cnscud/cavedemo/web
    depends_on:
      - ms-gateway



