apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cnscud-kafka
spec:
  replicas: 1
  serviceName: cavedemo-kafka
  selector:
    matchLabels:
      name: cavedemo-kafka
  template:
    metadata:
      labels:
        name: cavedemo-kafka
    spec:
      containers:
        - name: cnscud-kafka
          image: wurstmeister/kafka
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: cavedemo-kafka
            - name: KAFKA_CREATE_TOPICS
              value: test:1:1
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: cavedemo-zookeeper:2181/cnscud-kafka
          ports:
            - containerPort: 9092
              name: kafka
          volumeMounts:
            - mountPath: /kafka
              name: cavedemo-kafkadata-claim
      volumes:
        - name: cavedemo-kafkadata-claim
          persistentVolumeClaim:
            claimName: cavedemo-kafkadata-claim

---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: cavedemo-kafka
  name: cavedemo-kafka
spec:
  type: NodePort
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      nodePort: 30092
  selector:
    name: cavedemo-kafka

