apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ms-gateway
  template:
    metadata:
      labels:
        name: ms-gateway
    spec:
      containers:
        - image: cnscud/cavedemo-ms-gateway:1.0
          name: ms-gateway
          env:
            - name: ZK_HOSTS
              value: "cavedemo-zookeeper:2181"
          ports:
            - containerPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: ms-gateway
  name: ms-gateway
spec:
  ports:
    - name: "ms-gateway"
      port: 8900
      targetPort: 8900
  selector:
    name: ms-gateway
