apiVersion: v1
kind: ConfigMap
metadata:
  name: cavedemo-redis-conf
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    pidfile .pid
    appendonly yes
    cluster-config-file nodes-6379.conf
    pidfile /data/middleware-data/redis/log/redis-6379.pid
    cluster-config-file /data/middleware-data/redis/conf/redis.conf
    dir /data/middleware-data/redis/data/
    logfile "/data/middleware-data/redis/log/redis-6379.log"
    cluster-node-timeout 5000
    protected-mode no

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cavedemo-redis-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cavedemo-redis
spec:
  replicas: 1
  serviceName: cavedemo-redis
  selector:
    matchLabels:
      name: cavedemo-redis
  template:
    metadata:
      labels:
        name: cavedemo-redis
    spec:
      initContainers:
        - name: init-redis
          image: busybox
          command: ['sh', '-c', 'mkdir -p /data/middleware-data/redis/log/;mkdir -p /data/middleware-data/redis/conf/;mkdir -p /data/middleware-data/redis/data/']
          volumeMounts:
            - name: data
              mountPath: /data/middleware-data/redis/
      containers:
        - name: cavedemo-redis
          image: redis:5.0
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - "exec redis-server /data/middleware-data/redis/conf/redis.conf"
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP

          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 500m
              memory: 200Mi
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 300
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          volumeMounts:
            - name: cavedemo-redis-config
              mountPath: /data/middleware-data/redis/conf/
            - name: data
              mountPath: /data/middleware-data/redis/
      volumes:
        - name: cavedemo-redis-config
          configMap:
            name: cavedemo-redis-conf
        - name: data
          persistentVolumeClaim:
            claimName: cavedemo-redis-claim

---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: cavedemo-redis
  name: cavedemo-redis
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 30079
  selector:
    name: cavedemo-redis

