apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-fundmain-service
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ms-fundmain-service
  template:
    metadata:
      labels:
        name: ms-fundmain-service
    spec:
      containers:
        - image: cnscud/cavedemo-ms-fundmain-service:1.0
          name: ms-fundmain-service
          env:
            - name: ZK_HOSTS
              value: "cavedemo-zookeeper:2181"
          ports:
            - containerPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: ms-fundmain-service
  name: ms-fundmain-service
spec:
  ports:
    - name: "ms-fundmain"
      port: 9001
      targetPort: 9001
  selector:
    name: ms-fundmain-service
