kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cavedemo-mysql-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cavedemo-redis-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cavedemo-zkdata-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cavedemo-zkdatalog-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cavedemo-kafkadata-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

