server:
  port: 8900

spring:
  application:
    name: ms-gateway
  main:
    allow-bean-definition-overriding: true
  redis:
    host: cd-rd1.cnscud.com
    port: 6379
    database: 0
  cloud:
    zookeeper:
      connect-string: ${ZK_HOSTS:cd-zk1.cnscud.com:2181}
      discovery:
        enabled: true
        preferIpAddress: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: default
          uri: lb://ms-fundmain-service
          predicates:
            - Path=/fundmain/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: fetchIngredients
                fallbackUri: forward:/defaultfallback
                statusCodes:
                  - 500
                  - "NOT_FOUND"
            - name: Retry
              args:
                retries: 2
                series: SERVER_ERROR
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 30

        - id: testoutsidefallback
          uri: lb://ms-fundmain-service
          predicates:
            - Path=/fundmain2/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: fetchIngredients
                fallbackUri: forward:/externalfallback
                statusCodes:
                  - 500
                  - "NOT_FOUND"
            - name: Retry
              args:
                retries: 2
                series: SERVER_ERROR
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 30

        - id: ingredients-fallback
          uri: lb://ms-fundmain-service
          predicates:
            - Path=/externalfallback
          filters:
            - name: FallbackHeaders
              args:
                executionExceptionTypeHeaderName: Exception-Type
                executionExceptionMessageHeaderName: Exception-Message

logging:
  level:
    org.springframework.cloud: info
    com.cnscud.cavedemo.gateway: debug

