# 此文件被备忘, 用于记录单个数据源的配置

server:
  port: 9001

spring:
  application:
    name: ms-fundmain-service
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        enabled: true
  datasource:
    # 默认数据源
    url: jdbc:mysql://127.0.0.1:3306/cavedemo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: dbuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/cnscud/cavedemo/fundmain/mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.cnscud.cavedemo.fundmain.model.*



logging:
  level:
    org.springframework.cloud: debug
    com.cnscud.cavedemo: debug
